spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jdbc?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: ["/META-INF/resources/","classpath:/resources/","classpath:/static/","classpath:/public/","classpath:/webapp/","classpath:/templates/"]
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true